# Generated by Django 5.0.2 on 2024-02-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nav_color', models.CharField(default='#212529', max_length=20)),
                ('body_color', models.CharField(default='#fff', max_length=20)),
            ],
        ),
    ]
