# Generated by Django 5.0.2 on 2024-02-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
