# Generated by Django 5.0.2 on 2024-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_emailverificationtoken_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
