# Generated by Django 5.0.2 on 2024-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_remove_emailverificationtoken_time_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
